# ============================================================================
# STANDARD ANDROID & COMPILING REFLECTION RULES
# ============================================================================

# Suppress generic annotations warnings generated by compilation stubs
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.ParametersAreNonnullByDefault

# Preserve essential metadata attributes required for JSON parsing and reflection
-keepattributes Circle,InnerClasses,EnclosingMethod,Signature,*Annotation*,SourceFile,LineNumberTable

# Retain line number mapping information to output readable production crash stacktraces
-renamesourcefileattribute SourceFile

# ============================================================================
# ROOM DATABASE ENGINE OPTIMIZATIONS
# ============================================================================

# Allow R8 to optimize Room itself, but preserve structural internal architecture interfaces
-keep class * extends androidx.room.RoomDatabase
-keep class * extends androidx.room.migration.Migration

# Retain generative code frameworks utilized by Room runtime reflections
-keep class androidx.room.Room
-dontwarn androidx.room.paging.**

# Retain custom TypeConverters and initialization hooks
-keepclassmembers class * extends androidx.room.RoomDatabase {
    <init>(...);
    public *;
}

# ============================================================================
# PROJECT DATA ENTITIES (Prevents DB mapping fields from being stripped out)
# ============================================================================

-keep class com.ak.battleship.data.Game {
    <fields>;
    <init>(...);
}
-keep class com.ak.battleship.data.Move {
    <fields>;
    <init>(...);
}
-keep class com.ak.battleship.data.OpponentProfile {
    <fields>;
    <init>(...);
}

# ============================================================================
# LOTTIE ANIMATIONS REFLECTION PROTECTION (Required for confetti.json)
# ============================================================================

# Protect internal model layout nodes parsed via your JSON configuration assets
-keep class com.airbnb.lottie.** { *; }
-keep interface com.airbnb.lottie.** { *; }
-dontwarn com.airbnb.lottie.**

# Keep Room entities safe from obfuscation
-keep class com.ak.battleship.data.Game { *; }
-keep class com.ak.battleship.data.Move { *; }
-keep class com.ak.battleship.data.OpponentProfile { *; }

# Keep TensorFlow Lite safe
-keep class org.tensorflow.lite.** { *; }